/usr/local/bin/rclone mount idrive: /Users/akmann/idrive \
     --allow-other \
     --dir-cache-time 5m \
     --vfs-cache-max-age 12h \
     --vfs-read-chunk-size 64M \
     --vfs-read-chunk-size-limit 2G \
     --vfs-cache-mode writes \
     --cache-dir=/Users/akmann/.rclone_cache \
     --buffer-size 32M \
     --umask 002 \
     --config /Users/akmann/.config/rclone/rclone.conf
